<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,700' rel='stylesheet' type='text/css'> -->

 	<link rel="stylesheet" href="../../css/fonts.css">
	<link rel="stylesheet" href="../../css/reset.css">
	<link rel="stylesheet" href="../../css/style.css">
	<link rel="stylesheet" href="../../css/animate.css">
	<link rel="stylesheet" href="../../css/font-awesome.min.css">
	<script src="../../js/modernizr.js"></script>
  	
	<title>Sistema de Predial</title>
</head>