	<main class="cd-main-content">  <!-- //Este  "main" termina en "content.inc" -->
		<nav class="cd-side-nav">
			<ul>
				<li class="cd-label">Menú</li>
				<li class="has-children inicio active">
					<a href="index.php">Inicio</a>
					<ul>
						<li><a href="#">Sub Menú</a></li>
						<li><a href="#">Sub Menú</a></li>
						<li><a href="#">Sub Menú</a></li>
					</ul>
				</li>

				<li class="has-children generico"> <!-- //menu generico -->
					<a href="#">Menú</a>
					
					<ul>
						<li><a href="#">Sub Menú</a></li>
						<li><a href="#">Sub Menú</a></li>
						<li><a href="#">Sub Menú</a></li>
					</ul>
				</li>
				<li class="has-children generico"> <!-- //menu generico -->
					<a href="#">Menú</a>
					
					<ul>
						<li><a href="#">Sub Menú</a></li>
						<li><a href="#">Sub Menú</a></li>
						<li><a href="#">Sub Menú</a></li>
					</ul>
				</li>
				<li class="has-children generico"> <!-- //menu generico -->
					<a href="#">Menú</a>
					
					<ul>
						<li><a href="#">Sub Menú</a></li>
						<li><a href="#">Sub Menú</a></li>
						<li><a href="#">Sub Menú</a></li>
					</ul>
				</li>
				
			</ul>

			<ul>
				<li class="cd-label">Menú Secundario</li>

				<li class="has-children generico"> <!-- //menu generico -->
					<a href="#">Menú</a>
					
					<ul>
						<li><a href="#">Sub Menú</a></li>
						<li><a href="#">Sub Menú</a></li>
						<li><a href="#">Sub Menú</a></li>
					</ul>
				</li>

				<li class="has-children generico"> <!-- //menu generico -->
					<a href="#">Menú</a>
					
					<ul>
						<li><a href="#">Sub Menú</a></li>
						<li><a href="#">Sub Menú</a></li>
						<li><a href="#">Sub Menú</a></li>
					</ul>
				</li>

				<li class="has-children generico"> <!-- //menu generico -->
					<a href="#">Menú</a>
					
					<ul>
						<li><a href="#">Sub Menú</a></li>
						<li><a href="#">Sub Menú</a></li>
						<li><a href="#">Sub Menú</a></li>
					</ul>
				</li>

				<li class="has-children generico"> <!-- //menu generico -->
					<a href="#">Menú</a>
					
					<ul>
						<li><a href="#">Sub Menú</a></li>
						<li><a href="#">Sub Menú</a></li>
						<li><a href="#">Sub Menú</a></li>
					</ul>
				</li>
				
			</ul>

			<ul>
				<li class="cd-label">Terminar Sesión</li>
				<li class="action-btn"><a href="#">Salir</a></li>
			</ul>
		</nav>